### PR TITLE
WL-3708 : Javascript error from newline \n character in properties file

### PR DESCRIPTION
**Pull request by nicholaswilson100**
'\n' doesn't work in feedback submodule properties files
as the backslash has a special meaning in them (as a sign that there's more
 of the property to come on the next line).
I've put in the Java instead.

### CODE REVIEW

**Comment by buckett** [comment]
Ah, because the bundle is shared between both Java and JavaScript.

**Comment by nicholaswilson100** [comment]
Yup,  In FeedbackTool.java it first loads the properties into a Map request attribute, then in a jsp converts them to a javascript array, passes that array to handelbars, and then after the form is submitted Java (SakaiProxy) accesses them (again!). Doesn't feel elegant.

**Comment by nicholaswilson100** [comment]
but I guess if you're going to use handlebars that's what you have to do.... how else could you get at a properties file from javascript?

**Comment by nicholaswilson100** [comment]
ajax call

**Pull request merged**
