### PR TITLE
WL-3602 : re-inserting code that got lost in merge

### PR DESCRIPTION
**Pull request by nicholaswilson100**
I just did a fresh checkout and re-applied the patches I had for the JIRAS.

This covers WL-3602, adding recaptcha to handlebars, WL-3598, WL-3566

### CODE REVIEW

**Comment by buckett** [comment]
This doesn't merge.

**Comment by buckett** [comment]
I'm not sure what I'm supposed to be reviewing as it's difficult evaluate a "fix"

**Comment by nicholaswilson100** [comment]
I thought I did a fresh checkout....so it should merge cleanly...

**Comment by buckett** [comment]
Did this locally and forced pushed to github.

**Pull request closed without merging**
